# Generated by Django 4.2.4 on 2023-09-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media')),
                ('ability', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('linkdin', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('degree_of_years', models.CharField(max_length=50)),
                ('degree_name', models.CharField(max_length=50)),
                ('clg_name', models.CharField(max_length=50)),
                ('years12th', models.CharField(max_length=50)),
                ('class_name12th', models.CharField(max_length=50)),
                ('school_name12th', models.CharField(max_length=50)),
                ('years10th', models.CharField(max_length=50)),
                ('class_name10th', models.CharField(max_length=50)),
                ('school_name10th', models.CharField(max_length=50)),
                ('language1', models.CharField(max_length=50)),
                ('percent1', models.CharField(max_length=50)),
                ('language2', models.CharField(max_length=50)),
                ('percent2', models.CharField(max_length=50)),
                ('working_in', models.CharField(max_length=50)),
                ('working_years', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('designation1', models.CharField(max_length=50)),
                ('working_in2', models.CharField(max_length=50)),
                ('working_years2', models.CharField(max_length=50)),
                ('company_name2', models.CharField(max_length=50)),
                ('designation2', models.CharField(max_length=50)),
                ('skills1', models.CharField(max_length=50)),
                ('percents1', models.CharField(max_length=50)),
                ('skills2', models.CharField(max_length=50)),
                ('percents2', models.CharField(max_length=50)),
                ('skills3', models.CharField(max_length=50)),
                ('percents3', models.CharField(max_length=50)),
                ('skills4', models.CharField(max_length=50)),
                ('percents4', models.CharField(max_length=50)),
                ('skills5', models.CharField(max_length=50)),
                ('percents5', models.CharField(max_length=50)),
                ('skills6', models.CharField(max_length=50)),
                ('percents6', models.CharField(max_length=50)),
                ('interest_1', models.CharField(max_length=50)),
                ('interest_2', models.CharField(max_length=50)),
                ('interest_3', models.CharField(max_length=50)),
                ('interest_4', models.CharField(max_length=50)),
            ],
        ),
    ]
